courses = ['mathematics','programming','data structureand algorithm']
print(courses)
print(len(courses))
print(courses[0])
print(courses[2])
print(courses[-1])
print(courses[-2])
print(courses[-3])
print(courses[1:2])
print(courses[0:2])
print(courses[1:])
courses.append('microcontroller')
print(courses)
courses.insert(1,'microcontroller')
print(courses)
courses_2 = ['daa','machine learning']
courses.insert(0,courses_2)
print(courses)
courses.append(courses_2)
print(courses)
courses.extend(courses_2)
print(courses)
courses.remove('programming')
print(courses)
courses.pop()
print(courses)

